#!/bin/bash

# this is a script for fast c:c and chmod settings

rm -rf var/cache/* && php bin/console c:c && php bin/console c:c --env=prod && chmod 777 var -R

chmod 0777 src/AdminBundle/Resources/Photos/ -R
chmod 0777 web/cache -R

