<?php

namespace AdminBundle\Repository;

/**
 * ExhibitOwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExhibitOwnerRepository extends \Doctrine\ORM\EntityRepository
{
}
