<?php

namespace AdminBundle\Repository;

/**
 * UssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UssRepository extends \Doctrine\ORM\EntityRepository
{
}
